before_install:
  - "sudo add-apt-repository ppa:koffeinflummi/armake -y"
  - "sudo apt-get update -q"
  - "sudo apt-get install armake -y"
  - "sudo apt-get install sshpass -y"
script:
  - "bash -x ./build.sh"
deploy:
  - provider: script
    skip_cleanup: true
    script: 
      - "echo 'rename incoming/@cnto_additions incoming/@cnto_additions.old\nmkdir incoming/@cnto_additions\nput -r ./@cnto_additions incoming/' | sshpass -e -- sftp -o StrictHostKeyChecking=no cnto-pipeline@repo.carpenoctem.co"
    on:
      branch: master
